services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=shorturldb'
      - 'MONGO_INITDB_ROOT_PASSWORD=pass'
      - 'MONGO_INITDB_ROOT_USERNAME=user'
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
